# Generated by Django 4.0.4 on 2022-06-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetId', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('createUser', models.CharField(max_length=50)),
                ('createDate', models.DateField()),
                ('editUser', models.CharField(max_length=50)),
                ('editDate', models.DateField()),
                ('project', models.CharField(max_length=50)),
                ('voucherNumber', models.CharField(max_length=50)),
                ('budgetProjectName', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('totalBudgetBeforeTax', models.FloatField()),
                ('totalBudgetAfterTax', models.FloatField()),
                ('totalValueTax', models.FloatField()),
                ('currencyType', models.CharField(max_length=50)),
            ],
        ),
    ]
