# Generated by Django 4.0.4 on 2022-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0002_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budgetId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
