# Generated by Django 4.0.4 on 2022-06-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0003_alter_budget_budgetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budgetId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
