# Generated by Django 4.0.4 on 2022-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0004_alter_budget_budgetid_alter_budget_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='createDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='editDate',
            field=models.CharField(max_length=50),
        ),
    ]
