# Generated by Django 4.0.4 on 2022-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0005_alter_budget_createdate_alter_budget_editdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='createDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='editDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
