# Generated by Django 4.0.4 on 2022-06-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0007_anotherbudget_alter_budget_totalbudgetaftertax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='createDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='editDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='totalBudgetAfterTax',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='totalBudgetBeforeTax',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='totalValueTax',
            field=models.CharField(max_length=50),
        ),
    ]
