# Generated by Django 4.0.4 on 2022-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0010_alter_budget_createdate_alter_budget_editdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='totalBudgetAfterTax',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='totalBudgetBeforeTax',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='totalValueTax',
            field=models.CharField(max_length=50),
        ),
    ]
